# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iOS 学习组
email: zy@zybug.com
description: iOS 学习组｜ 新的定义 新的开始
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://github.zybug.com" # the base hostname & protocol for your site
github_username:  zybug

# Build settings
markdown: kramdown
